services:
  downloader:
    image: alpine:latest
    working_dir: /app
    volumes:
      - ${PWD}:/app  # Монтируем всё содержимое текущей папки, чтобы был доступ к скрипту .sh
      - ./models:/app/models # Отдельно выделяем папку для моделей (для ясности)
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        apk add --no-cache curl bash gzip
        mkdir -p /app/models
        
        LANGS=("ru" "en" "es")

        # 1. Скачиваем LID модель (определитель языка)
        if [ ! -f "${MODELS_DIR}/lid.176.bin" ]; then
            echo "Downloading language ID model..."
            curl -L https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin -o "${MODELS_DIR}/lid.176.bin"
        fi

        # 2. Скачиваем языковые векторы
        for lang in "${LANGS[@]}"; do
            FILE="${MODELS_DIR}/cc.${lang}.300.bin"
            if [ ! -f "$FILE" ]; then
                echo "Downloading $lang model..."
                curl -L "https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.${lang}.300.bin.gz" | gunzip > "$FILE"

            else
                echo "$lang model already exists."
            fi
        done

        echo "All models are ready!"
  fintent:
    build: .
    depends_on:
      downloader:
        condition: service_completed_successfully # Ждет, пока downloader закончит работу
    volumes:
      - ./models:/app/models
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    #volumes:
      #- .:/app
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '${WORKERS:-4}'
          memory: ${MEMEORY:-8G}
    restart: always